Remove old policy before installing new policy Fail if new policy can't be installed

diff --git a/sbin/set_simp_selinux_policy b/sbin/set_simp_selinux_policy
--- a/sbin/set_simp_selinux_policy
+++ b/sbin/set_simp_selinux_policy
@@ -11,20 +11,26 @@ semodule_path=`which semodule 2>/dev/null`
 
 if [ $? -eq 0 ]; then
   if [ "${arg}" == 'install' ]; then
-    # Build and load policy to set selinux context to enable puppet to read from
-    # SIMP-related directories.
+    # Build and load policy to set selinux context to enable puppet to
+    # read from SIMP-related directories.
+
+    # Be sure to remove any conflicting old policies
+    for policy in "${old_policies[@]}"; do
+      $semodule_path --list | grep -q "${policy}"
+
+      if [ $? -eq 0 ]; then
+        $semodule_path -r "${policy}"
+      fi
+    done
 
     $semodule_path -n -i /usr/share/selinux/packages/simp.pp
 
+    if [ $? -ne 0 ]; then
+      echo "ERROR: Failed to install 'simp' selinux policy"
+      exit 2
+    fi
+
     if selinuxenabled; then
-
-      for policy in "${old_policies[@]}"; do
-        $semodule_path --list | grep -q "${policy}"
-
-        if [ $? -eq 0 ]; then
-          $semodule_path -r "${policy}"
-        fi
-      done
 
       load_policy
 
